---
- hosts: all
  become: yes

  tasks:
    - name: Add the jenkins user 
      user:
        name: jenkins 
        shell: /bin/bash
        update_password: always
        password: x25IEJ53jMOB2
        # password: "{{ newpassword|password_hash('sha512') }}"
        groups: adm,sudo,dip,plugdev,lxd
        append: yes
        state: present

    - name: Make jenkins part of sudoers.d
      copy:
        dest: "/etc/sudoers.d/jenkins"
        content: "jenkins ALL=(ALL) NOPASSWD:ALL"

