---
- name: simple playbook for testing
- hosts: virtualbox

  tasks:
    - name: Ping  
      ping:
    
    - name: Install Python 
      apt:
        name: python3
        state: present

    - name: Install Nginx 
      apt:
        name: nginx
        state: present

#    - name: Add the ansible user 
#      user:
#        name: ansible 
#        password: Ansible01!
#       state: present