---
- hosts: virtualbox
  become: yes

  tasks:
    - name: Add the ansible user 
      user:
        name: ansible 
        shell: /bin/bash
        update_password: always
        # password: Ansible01!
        password: "{{ newpassword|password_hash('sha512') }}"
        groups: adm,sudo,dip,plugdev,lxd
        append: yes
        state: present

    - name: Make ansible part of sudoers.d
      copy:
        dest: "/etc/sudoers.d/ansible"
        content: "ansible ALL=(ALL) NOPASSWD:ALL"